// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/entities.dart';
import 'models/study_material_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3064228194119418078),
    name: 'StudyMaterialChunk',
    lastPropertyId: const obx_int.IdUid(8, 437412348351122795),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2598589049826896965),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5529375067132612837),
        name: 'chunkText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3086812267608595717),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 8694986888996991617),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1763830374732793939),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8854098990874705111),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3113712581527360667),
        name: 'subject',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 4928417494289307449),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6121596925427334228),
        name: 'concept',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 437412348351122795),
        name: 'timestamp',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8941975338346690150),
    name: 'StudyDocument',
    lastPropertyId: const obx_int.IdUid(5, 4531727652314832831),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7607647303362742107),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1870372808757432861),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1744514735007757644),
        name: 'localFilePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2773503520830203613),
        name: 'uploadTimestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4531727652314832831),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4349026234618348329),
        relationField: 'category',
        relationTarget: 'SubjectCategory',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'chunks',
        srcEntity: 'VectorChunk',
        srcField: 'document',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4742912025923379784),
    name: 'SubjectCategory',
    lastPropertyId: const obx_int.IdUid(2, 1570391031656806115),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 519141216466200368),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1570391031656806115),
        name: 'name',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 390291190823523015),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'documents',
        srcEntity: 'StudyDocument',
        srcField: 'category',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2016848715032113386),
    name: 'VectorChunk',
    lastPropertyId: const obx_int.IdUid(6, 5316815391176554412),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1815981182203925404),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6182540209952566985),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3805226571811523813),
        name: 'pageNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4661757936388625865),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(5, 8984142996910810294),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3168099846097993867),
        name: 'documentId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 69587279203879575),
        relationField: 'document',
        relationTarget: 'StudyDocument',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5316815391176554412),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 2432427335133471248),
        relationField: 'category',
        relationTarget: 'SubjectCategory',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1127669671123944521),
    name: 'AppUsage',
    lastPropertyId: const obx_int.IdUid(3, 5494888615271622567),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1780976562424360879),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6969417744653981743),
        name: 'dateString',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 8713477894974690700),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5494888615271622567),
        name: 'secondsSpent',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4615735950152280642),
    name: 'UserAchievement',
    lastPropertyId: const obx_int.IdUid(4, 6210561772182978199),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3698845668575589310),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1086219793656774697),
        name: 'badgeName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 84806117286457639),
        name: 'reason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6210561772182978199),
        name: 'dateUnlocked',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 8660162433978449003),
    name: 'GeneratedStudyMaterial',
    lastPropertyId: const obx_int.IdUid(6, 2402316204652653426),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4542679948153753304),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4498985037983110694),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7224999844883018684),
        name: 'contentJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6614908952261359072),
        name: 'dateCreated',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6096376847826503250),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 2712875791683519289),
        relationField: 'category',
        relationTarget: 'SubjectCategory',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2402316204652653426),
        name: 'title',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 9073131737728509324),
    name: 'Badge',
    lastPropertyId: const obx_int.IdUid(5, 8478723598686388910),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7598050585263142419),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8022030281289817568),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 20028885825487557),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1390918196751860211),
        name: 'dateEarned',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8478723598686388910),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 8107507089714996423),
        relationField: 'category',
        relationTarget: 'SubjectCategory',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(8, 9073131737728509324),
    lastIndexId: const obx_int.IdUid(10, 8107507089714996423),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    StudyMaterialChunk: obx_int.EntityDefinition<StudyMaterialChunk>(
      model: _entities[0],
      toOneRelations: (StudyMaterialChunk object) => [],
      toManyRelations: (StudyMaterialChunk object) => {},
      getId: (StudyMaterialChunk object) => object.id,
      setId: (StudyMaterialChunk object, int id) {
        object.id = id;
      },
      objectToFB: (StudyMaterialChunk object, fb.Builder fbb) {
        final chunkTextOffset = fbb.writeString(object.chunkText);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        final fileNameOffset = fbb.writeString(object.fileName);
        final subjectOffset = fbb.writeString(object.subject);
        final conceptOffset = fbb.writeString(object.concept);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, chunkTextOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.addOffset(3, fileNameOffset);
        fbb.addInt64(4, object.pageNumber);
        fbb.addOffset(5, subjectOffset);
        fbb.addOffset(6, conceptOffset);
        fbb.addInt64(7, object.timestamp);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final chunkTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const obx_int.Float32ListReader().vTableGet(
          buffer,
          rootOffset,
          8,
          Float32List(0),
        );
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final pageNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final conceptParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final timestampParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = StudyMaterialChunk(
          id: idParam,
          chunkText: chunkTextParam,
          embedding: embeddingParam,
          fileName: fileNameParam,
          pageNumber: pageNumberParam,
          subject: subjectParam,
          concept: conceptParam,
          timestamp: timestampParam,
        );

        return object;
      },
    ),
    StudyDocument: obx_int.EntityDefinition<StudyDocument>(
      model: _entities[1],
      toOneRelations: (StudyDocument object) => [object.category],
      toManyRelations: (StudyDocument object) => {
        obx_int.RelInfo<VectorChunk>.toOneBacklink(
          5,
          object.id,
          (VectorChunk srcObject) => srcObject.document,
        ): object.chunks,
      },
      getId: (StudyDocument object) => object.id,
      setId: (StudyDocument object, int id) {
        object.id = id;
      },
      objectToFB: (StudyDocument object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final localFilePathOffset = fbb.writeString(object.localFilePath);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, localFilePathOffset);
        fbb.addInt64(3, object.uploadTimestamp.millisecondsSinceEpoch);
        fbb.addInt64(4, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final localFilePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final uploadTimestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = StudyDocument(
          id: idParam,
          title: titleParam,
          localFilePath: localFilePathParam,
          uploadTimestamp: uploadTimestampParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<StudyDocument>(
          object.chunks,
          store,
          obx_int.RelInfo<VectorChunk>.toOneBacklink(
            5,
            object.id,
            (VectorChunk srcObject) => srcObject.document,
          ),
        );
        return object;
      },
    ),
    SubjectCategory: obx_int.EntityDefinition<SubjectCategory>(
      model: _entities[2],
      toOneRelations: (SubjectCategory object) => [],
      toManyRelations: (SubjectCategory object) => {
        obx_int.RelInfo<StudyDocument>.toOneBacklink(
          5,
          object.id,
          (StudyDocument srcObject) => srcObject.category,
        ): object.documents,
      },
      getId: (SubjectCategory object) => object.id,
      setId: (SubjectCategory object, int id) {
        object.id = id;
      },
      objectToFB: (SubjectCategory object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = SubjectCategory(id: idParam, name: nameParam);
        obx_int.InternalToManyAccess.setRelInfo<SubjectCategory>(
          object.documents,
          store,
          obx_int.RelInfo<StudyDocument>.toOneBacklink(
            5,
            object.id,
            (StudyDocument srcObject) => srcObject.category,
          ),
        );
        return object;
      },
    ),
    VectorChunk: obx_int.EntityDefinition<VectorChunk>(
      model: _entities[3],
      toOneRelations: (VectorChunk object) => [
        object.document,
        object.category,
      ],
      toManyRelations: (VectorChunk object) => {},
      getId: (VectorChunk object) => object.id,
      setId: (VectorChunk object, int id) {
        object.id = id;
      },
      objectToFB: (VectorChunk object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addInt64(2, object.pageNumber);
        fbb.addOffset(3, embeddingOffset);
        fbb.addInt64(4, object.document.targetId);
        fbb.addInt64(5, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pageNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final embeddingParam = const obx_int.Float32ListReader()
            .vTableGetNullable(buffer, rootOffset, 10);
        final object = VectorChunk(
          id: idParam,
          text: textParam,
          pageNumber: pageNumberParam,
          embedding: embeddingParam,
        );
        object.document.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.document.attach(store);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
    AppUsage: obx_int.EntityDefinition<AppUsage>(
      model: _entities[4],
      toOneRelations: (AppUsage object) => [],
      toManyRelations: (AppUsage object) => {},
      getId: (AppUsage object) => object.id,
      setId: (AppUsage object, int id) {
        object.id = id;
      },
      objectToFB: (AppUsage object, fb.Builder fbb) {
        final dateStringOffset = fbb.writeString(object.dateString);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dateStringOffset);
        fbb.addInt64(2, object.secondsSpent);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dateStringParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final secondsSpentParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = AppUsage(
          id: idParam,
          dateString: dateStringParam,
          secondsSpent: secondsSpentParam,
        );

        return object;
      },
    ),
    UserAchievement: obx_int.EntityDefinition<UserAchievement>(
      model: _entities[5],
      toOneRelations: (UserAchievement object) => [],
      toManyRelations: (UserAchievement object) => {},
      getId: (UserAchievement object) => object.id,
      setId: (UserAchievement object, int id) {
        object.id = id;
      },
      objectToFB: (UserAchievement object, fb.Builder fbb) {
        final badgeNameOffset = fbb.writeString(object.badgeName);
        final reasonOffset = fbb.writeString(object.reason);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, badgeNameOffset);
        fbb.addOffset(2, reasonOffset);
        fbb.addInt64(3, object.dateUnlocked.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final badgeNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final reasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateUnlockedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = UserAchievement(
          id: idParam,
          badgeName: badgeNameParam,
          reason: reasonParam,
          dateUnlocked: dateUnlockedParam,
        );

        return object;
      },
    ),
    GeneratedStudyMaterial: obx_int.EntityDefinition<GeneratedStudyMaterial>(
      model: _entities[6],
      toOneRelations: (GeneratedStudyMaterial object) => [object.category],
      toManyRelations: (GeneratedStudyMaterial object) => {},
      getId: (GeneratedStudyMaterial object) => object.id,
      setId: (GeneratedStudyMaterial object, int id) {
        object.id = id;
      },
      objectToFB: (GeneratedStudyMaterial object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final contentJsonOffset = fbb.writeString(object.contentJson);
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addOffset(2, contentJsonOffset);
        fbb.addInt64(3, object.dateCreated.millisecondsSinceEpoch);
        fbb.addInt64(4, object.category.targetId);
        fbb.addOffset(5, titleOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateCreatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = GeneratedStudyMaterial(
          id: idParam,
          type: typeParam,
          contentJson: contentJsonParam,
          dateCreated: dateCreatedParam,
          title: titleParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
    Badge: obx_int.EntityDefinition<Badge>(
      model: _entities[7],
      toOneRelations: (Badge object) => [object.category],
      toManyRelations: (Badge object) => {},
      getId: (Badge object) => object.id,
      setId: (Badge object, int id) {
        object.id = id;
      },
      objectToFB: (Badge object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addInt64(3, object.dateEarned.millisecondsSinceEpoch);
        fbb.addInt64(4, object.category.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final dateEarnedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = Badge(
          id: idParam,
          name: nameParam,
          description: descriptionParam,
          dateEarned: dateEarnedParam,
        );
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.category.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [StudyMaterialChunk] entity fields to define ObjectBox queries.
class StudyMaterialChunk_ {
  /// See [StudyMaterialChunk.id].
  static final id = obx.QueryIntegerProperty<StudyMaterialChunk>(
    _entities[0].properties[0],
  );

  /// See [StudyMaterialChunk.chunkText].
  static final chunkText = obx.QueryStringProperty<StudyMaterialChunk>(
    _entities[0].properties[1],
  );

  /// See [StudyMaterialChunk.embedding].
  static final embedding = obx.QueryHnswProperty<StudyMaterialChunk>(
    _entities[0].properties[2],
  );

  /// See [StudyMaterialChunk.fileName].
  static final fileName = obx.QueryStringProperty<StudyMaterialChunk>(
    _entities[0].properties[3],
  );

  /// See [StudyMaterialChunk.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<StudyMaterialChunk>(
    _entities[0].properties[4],
  );

  /// See [StudyMaterialChunk.subject].
  static final subject = obx.QueryStringProperty<StudyMaterialChunk>(
    _entities[0].properties[5],
  );

  /// See [StudyMaterialChunk.concept].
  static final concept = obx.QueryStringProperty<StudyMaterialChunk>(
    _entities[0].properties[6],
  );

  /// See [StudyMaterialChunk.timestamp].
  static final timestamp = obx.QueryIntegerProperty<StudyMaterialChunk>(
    _entities[0].properties[7],
  );
}

/// [StudyDocument] entity fields to define ObjectBox queries.
class StudyDocument_ {
  /// See [StudyDocument.id].
  static final id = obx.QueryIntegerProperty<StudyDocument>(
    _entities[1].properties[0],
  );

  /// See [StudyDocument.title].
  static final title = obx.QueryStringProperty<StudyDocument>(
    _entities[1].properties[1],
  );

  /// See [StudyDocument.localFilePath].
  static final localFilePath = obx.QueryStringProperty<StudyDocument>(
    _entities[1].properties[2],
  );

  /// See [StudyDocument.uploadTimestamp].
  static final uploadTimestamp = obx.QueryDateProperty<StudyDocument>(
    _entities[1].properties[3],
  );

  /// See [StudyDocument.category].
  static final category =
      obx.QueryRelationToOne<StudyDocument, SubjectCategory>(
        _entities[1].properties[4],
      );

  /// see [StudyDocument.chunks]
  static final chunks = obx.QueryBacklinkToMany<VectorChunk, StudyDocument>(
    VectorChunk_.document,
  );
}

/// [SubjectCategory] entity fields to define ObjectBox queries.
class SubjectCategory_ {
  /// See [SubjectCategory.id].
  static final id = obx.QueryIntegerProperty<SubjectCategory>(
    _entities[2].properties[0],
  );

  /// See [SubjectCategory.name].
  static final name = obx.QueryStringProperty<SubjectCategory>(
    _entities[2].properties[1],
  );

  /// see [SubjectCategory.documents]
  static final documents =
      obx.QueryBacklinkToMany<StudyDocument, SubjectCategory>(
        StudyDocument_.category,
      );
}

/// [VectorChunk] entity fields to define ObjectBox queries.
class VectorChunk_ {
  /// See [VectorChunk.id].
  static final id = obx.QueryIntegerProperty<VectorChunk>(
    _entities[3].properties[0],
  );

  /// See [VectorChunk.text].
  static final text = obx.QueryStringProperty<VectorChunk>(
    _entities[3].properties[1],
  );

  /// See [VectorChunk.pageNumber].
  static final pageNumber = obx.QueryIntegerProperty<VectorChunk>(
    _entities[3].properties[2],
  );

  /// See [VectorChunk.embedding].
  static final embedding = obx.QueryHnswProperty<VectorChunk>(
    _entities[3].properties[3],
  );

  /// See [VectorChunk.document].
  static final document = obx.QueryRelationToOne<VectorChunk, StudyDocument>(
    _entities[3].properties[4],
  );

  /// See [VectorChunk.category].
  static final category = obx.QueryRelationToOne<VectorChunk, SubjectCategory>(
    _entities[3].properties[5],
  );
}

/// [AppUsage] entity fields to define ObjectBox queries.
class AppUsage_ {
  /// See [AppUsage.id].
  static final id = obx.QueryIntegerProperty<AppUsage>(
    _entities[4].properties[0],
  );

  /// See [AppUsage.dateString].
  static final dateString = obx.QueryStringProperty<AppUsage>(
    _entities[4].properties[1],
  );

  /// See [AppUsage.secondsSpent].
  static final secondsSpent = obx.QueryIntegerProperty<AppUsage>(
    _entities[4].properties[2],
  );
}

/// [UserAchievement] entity fields to define ObjectBox queries.
class UserAchievement_ {
  /// See [UserAchievement.id].
  static final id = obx.QueryIntegerProperty<UserAchievement>(
    _entities[5].properties[0],
  );

  /// See [UserAchievement.badgeName].
  static final badgeName = obx.QueryStringProperty<UserAchievement>(
    _entities[5].properties[1],
  );

  /// See [UserAchievement.reason].
  static final reason = obx.QueryStringProperty<UserAchievement>(
    _entities[5].properties[2],
  );

  /// See [UserAchievement.dateUnlocked].
  static final dateUnlocked = obx.QueryDateProperty<UserAchievement>(
    _entities[5].properties[3],
  );
}

/// [GeneratedStudyMaterial] entity fields to define ObjectBox queries.
class GeneratedStudyMaterial_ {
  /// See [GeneratedStudyMaterial.id].
  static final id = obx.QueryIntegerProperty<GeneratedStudyMaterial>(
    _entities[6].properties[0],
  );

  /// See [GeneratedStudyMaterial.type].
  static final type = obx.QueryStringProperty<GeneratedStudyMaterial>(
    _entities[6].properties[1],
  );

  /// See [GeneratedStudyMaterial.contentJson].
  static final contentJson = obx.QueryStringProperty<GeneratedStudyMaterial>(
    _entities[6].properties[2],
  );

  /// See [GeneratedStudyMaterial.dateCreated].
  static final dateCreated = obx.QueryDateProperty<GeneratedStudyMaterial>(
    _entities[6].properties[3],
  );

  /// See [GeneratedStudyMaterial.category].
  static final category =
      obx.QueryRelationToOne<GeneratedStudyMaterial, SubjectCategory>(
        _entities[6].properties[4],
      );

  /// See [GeneratedStudyMaterial.title].
  static final title = obx.QueryStringProperty<GeneratedStudyMaterial>(
    _entities[6].properties[5],
  );
}

/// [Badge] entity fields to define ObjectBox queries.
class Badge_ {
  /// See [Badge.id].
  static final id = obx.QueryIntegerProperty<Badge>(_entities[7].properties[0]);

  /// See [Badge.name].
  static final name = obx.QueryStringProperty<Badge>(
    _entities[7].properties[1],
  );

  /// See [Badge.description].
  static final description = obx.QueryStringProperty<Badge>(
    _entities[7].properties[2],
  );

  /// See [Badge.dateEarned].
  static final dateEarned = obx.QueryDateProperty<Badge>(
    _entities[7].properties[3],
  );

  /// See [Badge.category].
  static final category = obx.QueryRelationToOne<Badge, SubjectCategory>(
    _entities[7].properties[4],
  );
}
